### ISSUE TITLE
Error starting GUI.py

### ISSUE THREAD

**Issue by nalinipradash** [Ashutosh2003/Operator-Fill-GUI#1]
When starting the GUI.py file following error shows:

`Traceback (most recent call last):
  File "GUI.py", line 1, in <module>
    import dearpygui.dearpygui as dpg
ModuleNotFoundError: No module named 'dearpygui'`

**Comment by AsutoSSH** [comment]
Install DearPyGUI to solve this error. I haven't released standalone executable because this is a very early access build.
